services:
  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - mongos_router
    networks:
      app-network:
        ipv4_address: 173.17.0.2
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"

  # mongodb1:
  #   container_name: mongodb1
  #   image: dh-mirror.gitverse.ru/mongo:latest
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb1_data_container:/data/db

  configSrv:
    image: mongo:latest
    container_name: configSrv
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - ./scripts:/scripts
      - config-data:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.20
    command:
      [
        "mongos",
        "--configdb",
        "config_server/configSrv:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    volumes:
      - ./scripts:/scripts
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard01-a:
    image: mongo:latest
    container_name: shard01-a
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.31
    volumes:
      - ./scripts:/scripts
      - shard1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs-shard-01",
        "--bind_ip_all",
        "--port",
        "27101"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard01-b:
    image: mongo:latest
    container_name: shard01-b
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.32
    volumes:
      - ./scripts:/scripts
      - shard1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs-shard-01",
        "--bind_ip_all",
        "--port",
        "27102"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard01-c:
    image: mongo:latest
    container_name: shard01-c
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.33
    volumes:
      - ./scripts:/scripts
      - shard1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs-shard-01",
        "--bind_ip_all",
        "--port",
        "27103"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard02-a:
    image: mongo:latest
    container_name: shard02-a
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.41
    volumes:
      - ./scripts:/scripts
      - shard2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs-shard-02",
        "--bind_ip_all",
        "--port",
        "27201"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard02-b:
    image: mongo:latest
    container_name: shard02-b
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.42
    volumes:
      - ./scripts:/scripts
      - shard2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs-shard-02",
        "--bind_ip_all",
        "--port",
        "27202"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard02-c:
    image: mongo:latest
    container_name: shard02-c
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.43
    volumes:
      - ./scripts:/scripts
      - shard2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "rs-shard-02",
        "--bind_ip_all",
        "--port",
        "27203"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

volumes:
  config-data:
  shard1-data:
  shard2-data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/24
