name: Deploy Lesson2
on:
  push:
    branches:
      - schema_1
jobs:
  deploy_schema_1:
    runs-on: self-hosted
    steps:
      - name: Build
        run: |
          cd /home/oleg/projects/lesson2/architecture-sprint-2
          git checkout schema_1
          git pull
          export $(cat .env | xargs)
          docker-compose -f compose.yaml stop
          docker-compose -f compose.yaml up -d --build